nama = input ("siapa namamu")
kelas = input ("kamu kelas berapa")
umur = input ("berapa umurmu")
sekolah = input ("sekolah dimana kamu")
jurusan = input ("kamu jurusan apa")
hobi = input ("hobimu apa")
makanan = input ("makanan favorit mu apa")
musik = input ("musik favorit mu apa")
citacita = input ("citacitamu apa")
alamat = input ("kamu tinggal dimana")
print("nama saya adalah",nama,"saya kelas",kelas,"umur saya adalah",umur,"saya sekolah di",sekolah,"saya jurusan",jurusan,"hobi saya adalah",hobi,"makanan favorit saya adalah",makanan,"musik favorit saya adalah",musik,"citacita saya", citacita,"tempat tinggal saya adalah",alamat)